version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
   - source: /public
    destination: /home/ubuntu/public
hooks:
  AfterInstall:
    - location: afterinstall.sh
      runas: root
  ApplicationStart:
    - location: applicationstart.sh
      runas: root
